# Generated by Django 3.0.7 on 2020-06-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_delete_user_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_table',
        ),
    ]
